'use client';
import {useState,type FormEvent} from 'react';
import {messages,type MessageKey} from '@/messages';
import {formatCurrency,parseAmount,totals} from '@/lib/finance';
import {stateSchema,type FinancialState} from '@/lib/sync/schema';
import {builtinCategories,cashEvents,categoryExpenses,monthDate,payInvoice,projectedBalance,purchaseSchedule,shiftMonth,unpaidCharges} from '@/lib/planning';

type Props={canAsk?:boolean;state:FinancialState;month:string;change:(update:(s:FinancialState)=>FinancialState)=>void};
function useLabels(state:FinancialState){const t=messages[state.prefs.locale];return {t,money:(n:number)=>formatCurrency(n,state.prefs.locale,'BRL',state.prefs.hidden),category:(id:string)=>state.customCategories.find(c=>c.id===id)?.name||t[id as MessageKey]||id};}
export function Cards({state,month,change}:Props){
 const {t,money,category}=useLabels(state);const [error,setError]=useState('');const [form,setForm]=useState<'card'|'purchase'|''>('');
 const unpaid=unpaidCharges(state);const categories=[...builtinCategories,...state.customCategories.map(c=>c.id)];
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setError('');try{
  if(form==='card'){const card={id:crypto.randomUUID(),name:String(data.get('name')).trim(),limit:parseAmount(String(data.get('limit'))),closingDay:Number(data.get('closing')),dueDay:Number(data.get('due'))};stateSchema.parse({...state,cards:[...state.cards,card]});change(s=>({...s,cards:[...s.cards,card]}));}
  else{const card=state.cards.find(c=>c.id===data.get('card'))!;const amount=parseAmount(String(data.get('amount')));if(amount>card.limit-unpaid.filter(c=>c.cardId===card.id).reduce((sum,c)=>sum+c.amount,0))throw new Error(t.overLimit);const charges=purchaseSchedule(card,String(data.get('date')),amount,Number(data.get('count')),String(data.get('category')),String(data.get('description')).trim(),crypto.randomUUID());stateSchema.parse({...state,cardCharges:[...state.cardCharges,...charges]});change(s=>({...s,cardCharges:[...s.cardCharges,...charges]}));}
  setForm('');
 }catch(err){setError(err instanceof Error&&err.message===t.overLimit?t.overLimit:t.planningInvalid);}}
 return <div className="planning-stack"><div className="row"><button className="button primary" onClick={()=>{setForm('card');setError('')}}>{t.addCard}</button><button className="button" disabled={!state.cards.length} onClick={()=>{setForm('purchase');setError('')}}>{t.purchase}</button></div>
 {form&&<section className="panel planning-panel"><h2>{form==='card'?t.addCard:t.purchase}</h2><form onSubmit={submit}><div className="form-grid">{form==='card'?<><label>{t.cardName}<input name="name" required maxLength={50}/></label><label>{t.creditLimit}<input name="limit" required inputMode="decimal"/></label><label>{t.closing}<input name="closing" type="number" min={1} max={31} required defaultValue={22}/></label><label>{t.due}<input name="due" type="number" min={1} max={31} required defaultValue={29}/></label></>:<><label>{t.cards}<select name="card">{state.cards.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>{t.description}<input name="description" required maxLength={120}/></label><label>{t.amount} (BRL)<input name="amount" inputMode="decimal" required/></label><label>{t.purchaseDate}<input name="date" type="date" defaultValue={month+'-01'} required/></label><label>{t.installments}<input name="count" type="number" min={1} max={360} defaultValue={1} required/></label><label>{t.category}<select name="category">{categories.map(c=><option key={c} value={c}>{category(c)}</option>)}</select></label></>}</div><p>{t.cardRule}</p>{error&&<p role="alert" className="error">{error}</p>}<div className="row"><button className="button primary">{t.save}</button><button className="button" type="button" onClick={()=>setForm('')}>{t.cancel}</button></div></form></section>}
 {!state.cards.length&&<section className="panel planning-panel"><p>{t.noCards}</p></section>}
 <div className="account-grid">{state.cards.map(card=>{const open=unpaid.filter(c=>c.cardId===card.id);const used=open.reduce((sum,c)=>sum+c.amount,0);const invoice=open.filter(c=>c.date.startsWith(month));return <section className="panel planning-panel" key={card.id}><h2>{card.name}</h2><p>{t.availableCredit}</p><h3>{money(card.limit-used)}</h3>{!state.prefs.hidden&&<progress max={card.limit} value={used} aria-label={t.used}/>}<p>{t.closing}: {card.closingDay} · {t.due}: {card.dueDay}</p><h2>{t.invoice}: {money(invoice.reduce((sum,c)=>sum+c.amount,0))}</h2>{invoice.map(c=><div className="report-row" key={c.id}><span>{c.description}<small className="muted"> · {category(c.category)}</small></span><strong>{money(c.amount)}</strong></div>)}{invoice.length>0&&<form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);change(s=>payInvoice(s,card.id,month,String(data.get('account')),String(data.get('paidAt'))));}}><label>{t.account}<select name="account" required>{state.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>{t.paymentDate}<input name="paidAt" type="date" defaultValue={monthDate(month,card.dueDay)} required/></label><button className="button primary" disabled={!state.accounts.length}>{t.pay}</button>{!state.accounts.length&&<p>{t.accountFirst}</p>}</form>}<h2 className="planning-subheading">{t.futureInstallments}</h2>{Array.from(new Set(open.filter(c=>c.date.slice(0,7)>month).map(c=>c.date.slice(0,7)))).sort().map(m=><div className="report-row" key={m}><span>{m}</span><strong>{money(open.filter(c=>c.date.startsWith(m)).reduce((sum,c)=>sum+c.amount,0))}</strong></div>)}</section>})}</div><p>{t.cashBasis}</p></div>;
}
export function Calendar({state,month}:Props){const {t,money}=useLabels(state);const [selection,setSelection]=useState('');const selected=selection.startsWith(month)?selection:month+'-01';const events=cashEvents(state);const days=Number(monthDate(month,31).slice(-2));const offset=new Date(month+'-01T12:00:00Z').getUTCDay();return <div className="planning-stack"><section className="panel planning-panel"><p>{t.projected} {selected}</p><h3>{money(projectedBalance(state,selected))}</h3><p>{t.projectionNote}</p></section><section className="panel planning-panel"><div className="financial-calendar" role="group" aria-label={t.calendar}>{Array.from({length:7},(_,i)=><div className="calendar-weekday" key={'w'+i}>{new Intl.DateTimeFormat(state.prefs.locale,{weekday:'short',timeZone:'UTC'}).format(new Date(Date.UTC(2026,0,4+i)))}</div>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const date=monthDate(month,i+1);const entries=events.filter(e=>e.date===date);return <button className={`calendar-day ${date===selected?'selected':''}`} aria-label={`${date}: ${entries.length}`} aria-pressed={date===selected} key={date} onClick={()=>setSelection(date)}><strong>{i+1}</strong><div className="calendar-dots">{Array.from(new Set(entries.map(e=>e.kind))).map(kind=><i className={kind} key={kind}/>)}</div></button>})}</div><div className="row calendar-legend"><span>🟢 {t.income}</span><span>🔴 {t.expense}</span><span>🟣 {t.cards}</span></div><h2>{selected}</h2>{events.filter(e=>e.date===selected).map(e=><div className="report-row" key={e.kind+e.id}><span>{e.title} <small className="muted">{e.status==='paid'?t.paid:t.pending}</small></span><strong className={e.amount>0?'positive':''}>{money(e.amount)}</strong></div>)}{!events.some(e=>e.date===selected)&&<p>{t.noEvents}</p>}</section></div>;}
export function Categories({state,change}:Props){const {t,category}=useLabels(state);const [error,setError]=useState('');return <section className="panel planning-panel"><h2>{t.categories}</h2><form className="row" onSubmit={e=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get('name')).trim();if(!name)return;change(s=>({...s,customCategories:[...s.customCategories,{id:crypto.randomUUID(),name}]}));e.currentTarget.reset();}}><label>{t.categoryName}<input name="name" required maxLength={50}/></label><button className="button primary" disabled={state.customCategories.length>=100}>{t.addCategory}</button></form>{error&&<p role="alert">{error}</p>}{builtinCategories.map(c=><div className="report-row" key={c}>{category(c)}</div>)}{state.customCategories.map(c=><form className="row category-editor" key={c.id} onSubmit={e=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get('name')).trim();if(name)change(s=>({...s,customCategories:s.customCategories.map(x=>x.id===c.id?{...x,name}:x)}));}}><input name="name" defaultValue={c.name} aria-label={t.categoryName} required maxLength={50}/><button className="button">{t.rename}</button><button className="button" type="button" onClick={()=>{if(state.transactions.some(x=>x.category===c.id)||state.cardCharges.some(x=>x.category===c.id)||[state.limits,...Object.values(state.monthlyLimits)].some(l=>c.id in l)){setError(t.usedCategory);return;}change(s=>({...s,customCategories:s.customCategories.filter(x=>x.id!==c.id)}));setError('');}}>{t.deleteCategory}</button></form>)}</section>;}
export function ReportBreakdown({state,month}:Props){const {t,money,category}=useLabels(state);const previous=totals(state.transactions.filter(x=>x.date.startsWith(shiftMonth(month,-1))));const current=totals(state.transactions.filter(x=>x.date.startsWith(month)));return <section className="panel planning-panel"><h2>{t.categoryReport}</h2>{categoryExpenses(state,month).map(([id,value])=><div className="report-row" key={id}><span>{category(id)}</span><strong>{money(value)}</strong></div>)}<h2 className="planning-subheading">{t.comparison}</h2><p>{t.delta}: {money(current.expenses-previous.expenses)}</p><p>{t.cashBasis}</p></section>;}
export function FinancialAI({state,month,canAsk=false}:Props){const {t,money,category}=useLabels(state);const [question,setQuestion]=useState('');const [answer,setAnswer]=useState('');const [busy,setBusy]=useState(false);const top=categoryExpenses(state,month)[0];const current=totals(state.transactions.filter(x=>x.date.startsWith(month)));const previous=totals(state.transactions.filter(x=>x.date.startsWith(shiftMonth(month,-1))));const facts=[{q:t.topQuestion,a:top?`${category(top[0])}: ${money(top[1])}`:t.planningNoData},{q:t.forecastQuestion,a:`${t.projected}: ${money(projectedBalance(state,monthDate(month,31)))}`},{q:t.compareQuestion,a:`${t.delta}: ${money(current.expenses-previous.expenses)}`}];return <section className="panel planning-panel ai-panel"><h2>✨ Fynly AI</h2><p>{t.localAnalysis}</p><div className="planning-stack">{facts.map(f=><article className="ai-fact" key={f.q}><h2>{f.q}</h2><strong>{f.a}</strong></article>)}</div><p>{t.projectionNote}</p><form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setAnswer('');try{const response=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,month}),signal:AbortSignal.timeout(45000)});const result=await response.json();setAnswer(response.ok?result.answer:t.aiUnavailable);}catch{setAnswer(t.aiUnavailable);}finally{setBusy(false);}}}><label>{t.ask}<input value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000} required disabled={busy||state.prefs.hidden||!canAsk}/></label><p className="small">{t.aiNotice}</p>{!canAsk&&<p>{t.aiSyncRequired}</p>}<button className="button primary" disabled={busy||state.prefs.hidden||!canAsk}>{busy?t.busy:t.send}</button></form>{answer&&<div className="ai-answer" role="status">{state.prefs.hidden?'••••••':answer}</div>}</section>;}
